Practice_4/Models/BaseProduct.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Practice_4.Models {
    public class BaseProduct {
        [Key]
        public int Id { get; set; }

        [Display(Name="Название продукта")]
        [Required(ErrorMessage ="Название продукта не может быть пустым")]
        [RegularExpression(@"^[а-яА-ЯёЁa-zA-Z]+$", ErrorMessage = "Название должно включать буквенные символы")]
        public string Name { get; set; }

        [Display(Name = "Количество")]
        [Required(ErrorMessage ="Количество продуктов не может быть пустым")]
        public string Amount { get; set; }

        public BaseProduct() {}
        public BaseProduct(int id,string name,string amount) {
            Id = id;
            Name = name;
            Amount = amount;
        }
    }
}

Practice_4/Controllers/BaseProductController.cs
using Practice_4.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Practice_4.Controllers
{
    public class BaseProductController : Controller
    {
        [HttpGet]
        public ActionResult Create() {
            return View();
        }

        /// <summary>
        /// Метод добавления в коллекцию продукта
        /// </summary>
        /// <param name="product">Продукт переденный из формы</param>
        /// <returns>Переадресовывает на главную страницу</returns>
        [HttpPost]
        public ActionResult Create(BaseProduct product) {
            if (!ModelState.IsValid)
                return View();

            var products = (List<BaseProduct>)Session["BaseProducts"];

            if (products == null)
                products = new List<BaseProduct>();

            product.Id = products.Count == 0 ? 1 : products.Max(item => item.Id) + 1;

            products.Add(product);
            Session["BaseProducts"] = products;

            TempData["SuccessMessage"] = "Продукт успешно добавлен";

            return RedirectToAction("Index", "Products");
        }

        /// <summary>
        /// Метод получения информации о продукте
        /// </summary>
        /// <param name="id">id продукта</param>
        /// <returns>Страница с информацией о продукте</returns>
        [HttpGet]
        public ActionResult Details(int? id) {
            if (id == null)
                return RedirectToAction("Index", "Products");

            var products = ((List<BaseProduct>)Session["BaseProducts"]);

            if (products == null || products.Count == 0)
            {
                TempData["ErrorMessage"] = $"Невозможно отобразить информацию о продукте,коллекция продуктов отсутствует или пуста";
                return RedirectToAction("Index", "Products");
            }

            var productToDisplay = products.FirstOrDefault(product => product.Id == id);

            if (productToDisplay == null)
            {
                TempData["ErrorMessage"] = $"Продукт с идентификатором [{id}] не найден";
                return RedirectToAction("Index", "Products");
            }

            return View(productToDisplay);
        }

        [HttpGet]
        public ActionResult Edit(int? id) {
            if (id == null)
                return RedirectToAction("Index", "Products");

            var products = ((List<BaseProduct>)Session["BaseProducts"]);

            if (products == null || products.Count == 0)
            {
                TempData["ErrorMessage"] = $"Невозможно редактировать продукт,коллекция продуктов отсутствует или пуста";
                return RedirectToAction("Index", "Products");
            }

            var productToEdit = products.FirstOrDefault(product => product.Id == id);

            if (productToEdit == null)
            {
                TempData["ErrorMessage"] = $"Продукт с идентификатором [{id}] не найден";
                return RedirectToAction("Index", "Products");
            }

            return View(productToEdit);
        }

        /// <summary>
        /// Метод редактирования продукта
        /// </summary>
        /// <param name="product">редактированный продукт</param>
        /// <returns>Переадресация на главную страницу</returns>
        [HttpPost]
        public ActionResult Edit(BaseProduct product) {
            if (!ModelState.IsValid)
                return View(product);

            var products = (List<BaseProduct>)Session["BaseProducts"];

            if (products == null || products.Count == 0)
            {
                TempData["ErrorMessage"] = $"Невозможно редактировать продукт,коллекция продуктов отсутствует или пуста";
                return RedirectToAction("Index", "Products");
            }

            if (products.FirstOrDefault(item => item.Id == product.Id) == null)
            {
                TempData["ErrorMessage"] = $"Продукт с идентификатором [{product.Id}] не найден";
                return RedirectToAction("Index", "Products");
            }

            products[products.FindIndex(item => item.Id == product.Id)] = product;

            Session["BaseProducts"] = products;

            TempData["SuccessMessage"] = $"Продукт [{product.Name}] изменен!";
            return RedirectToAction("Index", "Products");
        }

        /// <summary>
        /// Метод удаления продукта из коллекции
        /// </summary>
        /// <param name="id">id продукта</param>
        /// <returns>Переадресация на главную страницу</returns>
        [HttpGet]
        public ActionResult Delete(int? id) {
            if (id == null)
                return RedirectToAction("Index", "Products");
            var products = (List<BaseProduct>)Session["BaseProducts"];

            if (products == null || products.Count == 0)
            {
                TempData["ErrorMessage"] = $"Невозможно удалить продукт,коллекция продуктов отсутствует или пуста"; return RedirectToAction("Index", "Products");
            }

            var product = products.Find(item => item.Id == id);

            if (product == null)
            {
                TempData["ErrorMessage"] = $"Продукт с идентификатором [{id}] не найден";
                return RedirectToAction("Index", "Products");
            }

            TempData["SuccessMessage"] = $"Продукт [{product.Name}] успешно удалён!";
            products.Remove(product);

            Session["BaseProducts"] = products;

            return RedirectToAction("Index", "Products");
        }
    }
}

Practice_4/Views/BaseProduct/Create.cshtml
@model Practice_4.Models.BaseProduct

@{
    ViewBag.Title = "Create";
}


@if (!ViewData.ModelState.IsValid)
{
    <div class="alert alert-danger" role="alert">
        @foreach (var modelstate in ViewData.ModelState.Values.Where(value => value.Errors.Count > 0))
        {
            foreach (var item in modelstate.Errors)
            {
                <p>@item.ErrorMessage</p>
            }
        }
    </div>
}
<h2>Добавление продукта</h2>
@using (Html.BeginForm("Create", "BaseProduct", FormMethod.Post))
{
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => Model.Name, new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => Model.Name, new { htmlAttributes = new { @class = "form-control col-md-10" } })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => Model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => Model.Amount, new { htmlAttributes = new { @class = "form-control col-md-10" } })
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.ActionLink("Назад", "Index", "Products", null, new { @class = "btn btn-danger" })
                <button type="submit" class="btn btn-success">Добавить</button>
            </div>
        </div>
    </div>


}

Practice_4/Views/BaseProduct/Details.cshtml
@model Practice_4.Models.BaseProduct

@{
    ViewBag.Title = "Index";
}

<h2>Подробности</h2>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

    </dl>
</div>
<p>
    <div class="form-group">
        @Html.ActionLink("Назад", "Index", "Products", null, new { @class = "btn btn-success" })
        @Html.ActionLink("Редактировать", "Edit", null, new { id = Model.Id }, new { @class = "btn btn-primary" })
        @Html.ActionLink("Удалить", "Delete",null, new { id = Model.Id }, new { @class = "btn btn-danger", @onclick = "return confirm('Вы действительно хотите удалить продукт ?')" })

    </div>
</p>

Practice_4/Views/BaseProduct/Edit.cshtml
@model Practice_4.Models.BaseProduct

@{
    ViewBag.Title = "Edit";
}


@if (!ViewData.ModelState.IsValid)
{
    <div class="alert alert-danger" role="alert">
        @foreach (var modelstate in ViewData.ModelState.Values.Where(value => value.Errors.Count > 0))
        {
            foreach (var item in modelstate.Errors)
            {
                <p>@item.ErrorMessage</p>
            }
        }
    </div>
}
<h2>Редактирование</h2>

@using (Html.BeginForm("Edit", "BaseProduct", FormMethod.Post))
{
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => Model.Name, new { htmlAttributes = new { @class = "form-control col-md-10" } })
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control col-md-10" } })
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.ActionLink("Назад", "Index", "Products", null, new { @class = "btn btn-danger" })
                <button type="submit" class="btn btn-success">Подвердить</button>
            </div>
        </div>
    </div>

}